<?php

namespace tdt4237\webapp;

use Symfony\Component\Config\Definition\Exception\Exception;

class Hash
{

//    static $salt = "password";


    public function __construct()
    {
    }

    public static function make($plaintext)
    {
        return password_hash($plaintext, PASSWORD_DEFAULT); //use the bcrypt algorithm (salt is randomly generated by default)
    }

    public function check($plaintext, $hash)
    {
        return password_verify($plaintext, $hash); //verify the hash
    }

}
